### ISSUE TITLE
lowcode 下目录配置是如何生成的

### ISSUE THREAD

**Issue by haledeng** [Dogtiti/next-pro-lowcode-materials#1]
lowcode 目录下的组件配置是怎么生成的，应该不是通过 npm script 跑出来的吧？看着像是手写的。

**Comment by Dogtiti** [comment]
@haledeng 第一次如果从src导出了type会根据type自动生成低代码描述，之后如果已经生成过lowcode文件夹了就不会再自动生成低代码描述了，我这边是手动填写的低代码描述，自动生成的基本上都得改 不如直接手动填
